# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
name: Cron
on:
  schedule:
    # Executa a cada 5 minutos
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - run: date

  cron-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every 5 minutes
        run: echo "This workflow runs every 5 minutes"
