name: Cypress Tests

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  # schedule:
  #   - cron: '*/59 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - run: date

  cron-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every 30 minutes
        run: echo "This workflow runs every 15 minutes"

  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test

      - name: Send notification to Matsu server on Discord when failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"username": "GitHub Actions", "content": "**Ingressos do LP em SP liberados!** Você pode comprar aqui: https://linkinpark.com/tour"}' \
               $DISCORD_MATSU_WEBHOOK_URL
        env:
          DISCORD_MATSU_WEBHOOK_URL: ${{ secrets.DISCORD_MATSU_WEBHOOK_URL }}
